// Generates src/pages.generated.ts embedding every file under
// packages/frontend/public as base64 string constants — mirrors the
// reference TVMasjid cloud/pages.mjs trick (module imports are traced by
// nft/esbuild; dynamic fs reads at runtime are not).
//
// Run: node scripts/gen-pages.mjs   (also run by build.mjs before esbuild)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.join(__dirname, '..');
// Cloud-variant frontend (from reference cloud/pages.mjs): admin.html carries
// the superuser console (login as "admin"), license UI, and Blob uploads.
const publicDir = path.join(pkgRoot, '..', 'frontend', 'public-cloud');
const outFile = path.join(pkgRoot, 'src', 'pages.generated.ts');

const files = [];
function walk(dir, prefix = '') {
  for (const e of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (e.isDirectory()) walk(path.join(dir, e.name), `${prefix}/${e.name}`);
    else files.push({ url: `${prefix}/${e.name}`, file: path.join(dir, e.name) });
  }
}
walk(publicDir);

// Hanya benamkan halaman HTML + sw.js dalam fungsi. CSS/JS/imej/vendor/manifest
// kini disalin ke .vercel/output/static oleh build.mjs (lihat nota di sana) dan
// dihidangkan dari CDN Vercel — bukan melalui fungsi serverless. Mengecilkan
// ASSETS ini memendekkan cold-start (tiada lagi hls.min.js/display.css base64
// dalam bundle).
const KEEP = new Set(['/admin.html', '/display.html', '/guide.html', '/sw.js']);
const embedded = files.filter((f) => KEEP.has(f.url));

const lines = [
  '// AUTO-GENERATED by scripts/gen-pages.mjs — do not edit.',
  '// Frontend public/ assets embedded so esbuild bundles them into the',
  '// serverless function (parity with reference cloud/pages.mjs).',
  ''
];

for (const f of embedded) {
  const b64 = fs.readFileSync(f.file).toString('base64');
  lines.push(`export const A_${b64Name(f.url)} = "${b64}";`);
}

lines.push('');
lines.push('export const ASSETS: Record<string, string> = {');
for (const f of embedded) lines.push(`  '${f.url}': A_${b64Name(f.url)},`);
lines.push('};');
lines.push('');

fs.writeFileSync(outFile, lines.join('\n'));
console.log(`[gen-pages] embedded ${embedded.length} assets (${embedded.map((f) => f.url).join(', ')}) -> ${path.relative(pkgRoot, outFile)}`);

function b64Name(url) {
  return url.slice(1).replace(/[^a-zA-Z0-9]/g, '_');
}
